name: Workflow
on:
  push:
    branches:
      - main
 
jobs:
  job1:
    #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    if: ${{ github.event_name == 'push'  }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.5"
      - name: Set version
        run: | 
          VERSION=$(grep "version:" pubspec.yaml | awk '{print $2}')
          echo version $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Pub get
        run: flutter pub get
      - name: Tests
        run: flutter test
      - name: Build
        run: flutter build apk --release
      - name: Deploy
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ env.VERSION }}
          token: ${{ secrets.ACCESS_TOKEN }}